### ISSUE TITLE
Add "page_number" as an argument for functions where "page_size" is already an argument

### ISSUE THREAD

**Issue by benjaminrobinson** [vusaverse/vvtableau#3]
It would be great to be able to paginate through functions such as `get_server_views` where I might have more than 1000 views on my Tableau Server and want to be able to identify all views for use in other `vvtableau` functions.  Could you add `page_number` as an argument in these functions?  Thanks!  This is a super great package that we will definitely be taking advantage of at my company.

**Comment by tin900** [comment]
Hi @benjaminrobinson 

The following commit (a411d75ddcbb58d190840f8c442acca7c8cad368) adds `page_number` as an argument in the functions.

**Comment by tin900** [comment]
Hi @benjaminrobinson,

The new version of `vvtableau` has been published to CRAN, therefore I will now close this issue.
