### ISSUE TITLE
Pulling Specific Sheet Data from Dashboards

### ISSUE THREAD

**Issue by chasebinns27** [vusaverse/vvtableau#5]
Hi! I have been using the `get_server_views` function to identify the IDs of views that I would like to download with the `download_tableau_crosstab_excel` function. However, if the sheetType equals "dashboard", I have had challenges downloading the correct view data since the dashboard is composed of multiple sheets. Insight into how to go about downloading data from a dashboard view that has multiple sheets would be greatly appreciated! Thanks!

**Comment by chasebinns27** [comment]
Never mind. This is discussed here: https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_workbooks_and_views.htm#download_view_excel .

**Comment by tin900** [comment]
Hi @chasebinns27, 

Thank you for using the `vvtableau` package and for bringing this issue to our attention! 

It's unfortunate that downloading data from a dashboard view composed of multiple sheets is not currently supported by the Tableau Server REST API. 

We will add a note in the function roxygen description to inform users about this limitation. 


Kind regards,
Tomer

**Comment by tin900** [comment]
This commit adds the note to the function roxygen description: d50e5f15c15f373287ab4324939b1ca46f5683b1
